package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2

package_group(
    name = "sharedstream_public",
    includes = [
        "//src/main/java/com/google/android/libraries/feed/sharedstream:sharedstream_pkgs_and_users",
    ],
    packages = ["//..."],
)
