package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2

android_library(
    name = "fake_card_configuration",
    testonly = True,
    srcs = ["FakeCardConfiguration.java"],
    deps = [
        "//src/main/java/com/google/android/libraries/feed/host/stream",
        "@androidsdk//com.android.support:support-annotations-25.3.1",
    ],
)
